# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: giliguor
    role: Maintain
  - member: pamontag
    role: Maintain
  - member: nvandewalle
    role: Maintain